### ISSUE TITLE
About dungeon loot.

### ISSUE THREAD

**Issue by AbsoZeroPK** [Extex101/jelys_pizzaria#5]
I have a question?

I notice that this Mod is doing some changes to the Dungeon Loot.

Now I don't know, how many want to keep they Mapgen and/or Dungeon Loot by default, untouched, nothing new added to the Chests.

So is it possible, to add in the settings, an Option, that the Dungeon Loot don't get altered at all?

Hope this comment wasn't rude? If it was, I apologise.

**Comment by Extex101** [comment]
Dungeon Loot has an API to add items to the loot.
I have made cheese, sauce and some special items spawn occasionally in chests. 
There is also a rare item that can only be obtained that way.

**Comment by AbsoZeroPK** [comment]
I'm not a Programmer, and even in Lua I'm lost, so is it possible to explain it, simple, how to use the Dungeon Loot API, please?

**Comment by Extex101** [comment]
So the mod that adds chests to dungeons allows other mods to add things to the big list of possible items that can spawn. So I've added Cheese because it's one of the harder items to get, as well as an unobtainable special item.

So all I did was add to the list of possible loot, I didn't change any existing loot tables

**Comment by AbsoZeroPK** [comment]
Thanks for the answer.

Cheese is one of the harder items, without any other optional Mods enabled.
In mobs_animal you can get cheese (mobs:cheese), if you cook a bucket of milk.
Otherwise there is a cheese mod, too.

Can I write the Link to the Mod in here?
